variables:
  REGISTRY_IMAGE: 192.168.3.201:8082
  IMAGE_NAME: $REGISTRY_IMAGE/$CI_PROJECT_NAME:temp-$CI_COMMIT_SHORT_SHA # 开发镜像标签增加temp-前缀，方便仓库清理
  CONTAINER_NAME: $CI_PROJECT_NAME

stages:
  - test
  - publish
  - docker
  - deploy

before_script:
  - chmod +x gradlew

test:
  stage: test
  tags:
    - newbie
    - pve-200
  script:
    - ./gradlew test
  except:
    - master
    - tags

snapshot-publish:
  stage: publish
  tags:
    - newbie
    - pve-200
  script:
    - ./gradlew test
    - ./gradlew publishAllPublicationsToBjknrtRepository
  only:
    refs:
      - master

snapshot-docker:
  stage: docker
  tags:
    - newbie
    - pve-200
  script:
    - ./gradlew kotlin-data-server:jib -Djib.to.image=$IMAGE_NAME -DsendCredentialsOverHttp=true
  dependencies:
    - snapshot-publish
  only:
    refs:
      - master

snapshot-deploy:
  image: docker:git
  stage: deploy
  variables:
    SERVER_PROFILE: dev
    SERVER_PORT: 8080
    CONTAINER_EXPOSE_PORT: 8000 # TODO 修改访问端口
  tags:
    - newbie
    - pve-200
  script:
    - mkdir -p ~/.ssh
    - echo "$REVIEW_SSH_ID_RSA" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no -p $SNAPSHOT_SSH_PORT $SNAPSHOT_SSH_USER@$SNAPSHOT_SSH_HOST "docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true"
    - ssh -o StrictHostKeyChecking=no -p $SNAPSHOT_SSH_PORT $SNAPSHOT_SSH_USER@$SNAPSHOT_SSH_HOST "docker run -d --restart=always --name $CONTAINER_NAME -v /data/$CONTAINER_NAME/logs:/bjknrt/logs -v /etc/localtime:/etc/localtime -e TZ='Asia/Shanghai' -p $CONTAINER_EXPOSE_PORT:$SERVER_PORT $IMAGE_NAME --spring.profiles.active=$SERVER_PROFILE --server.port=$SERVER_PORT --spring.cloud.nacos.discovery.port=$CONTAINER_EXPOSE_PORT --spring.cloud.nacos.discovery.ip=$SNAPSHOT_SSH_HOST"
  dependencies:
    - snapshot-docker
  environment:
    name: snapshot/$CI_PROJECT_NAME
    url: http://$SNAPSHOT_SSH_HOST:$CONTAINER_EXPOSE_PORT/
    on_stop: stop-snapshot-deploy
  only:
    refs:
      - master

stop-snapshot-deploy:
  stage: deploy
  tags:
    - newbie
    - pve-200
  dependencies: [ ]
  when: manual
  script:
    - ssh -o StrictHostKeyChecking=no -p $SNAPSHOT_SSH_PORT $SNAPSHOT_SSH_USER@$SNAPSHOT_SSH_HOST "docker stop $CONTAINER_NAME || true && docker rm $CONTAINER_NAME || true"
  environment:
    name: snapshot/$CI_PROJECT_NAME
    action: stop
  only:
    refs:
      - master

include:
  - local: '.gitlab-release-ci.yml'