spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/medication_remind2?connectionTimeZone=SERVER&characterEncoding=utf8
    username: root
    password: 1234qwer
    druid:
      nacos:
        config:
          enabled: false
        discovery:
          enabled: false
  cloud:
    nacos:
      config:
        enabled: false
      discovery:
        enabled: false

logging:
  level:
    web: debug
    me: debug
    com:
      bjknrt: debug
    druid:
      sql:
        Statement: debug
        ResultSet: debug

